In [1]:
# Lo primero es importar la librería numpy que es una librería que nos permite el manejo de arreglos y matrices 
import numpy as np


In [2]:
# Ahora generamos una matriz de 4x4 elementos
M = np.array([[1, 9, 8, -4],
              [2, 3, 1, 2],
              [8, 1, -4, 6],
              [-3, 2, -3, 1]])
print(M)


[[ 1  9  8 -4]
 [ 2  3  1  2]
 [ 8  1 -4  6]
 [-3  2 -3  1]]


In [5]:
# Calculamos su matriz inversa:
try:
    M_inv = np.linalg.inv(M)
    print("Matriz inversa de M:")
    print(M_inv)
except np.linalg.LinAlgError:
    print("La matriz M no es invertible.")
    
# Para comprobar que efectivamente es la matriz inversa, multiplicamos M x M_inv y debe dar como resultado una matriz unitaria
producto = np.dot(M, M_inv)
# redondeamos cada elemento
producto_redondeado = np.round(producto, 2)
print("M × M_inv redondeado a 1 decimal:")
print(producto_redondeado)


Matriz inversa de M:
[[ 0.08456376 -0.26040268  0.15436242 -0.06711409]
 [ 0.09395973 -0.06711409  0.06040268  0.14765101]
 [-0.08322148  0.43087248 -0.16778523 -0.18791946]
 [-0.18389262  0.64563758 -0.16107383 -0.06040268]]
M × M_inv redondeado a 1 decimal:
[[ 1.  0.  0.  0.]
 [-0.  1. -0. -0.]
 [ 0.  0.  1.  0.]
 [-0.  0.  0.  1.]]


In [8]:
# Ahora calculamos la matriz traspuesta de M
M_T = M.T
print("Matriz M:")
print(M,"\n")
print("Matriz traspuesta de M:")
print(M_T)

Matriz M:
[[ 1  9  8 -4]
 [ 2  3  1  2]
 [ 8  1 -4  6]
 [-3  2 -3  1]] 

Matriz traspuesta de M:
[[ 1  2  8 -3]
 [ 9  3  1  2]
 [ 8  1 -4 -3]
 [-4  2  6  1]]


In [9]:
# Multiplicamos la matriz M por un escalar.
# Definimos el escalar
escalar = 3

# Multiplicamos la matriz M por el escalar
M_escalada = escalar * M

# Mostramos el resultado
print(f"Matriz M multiplicada por el escalar {escalar}:\n")
print(M_escalada)


Matriz M multiplicada por el escalar 3:

[[  3  27  24 -12]
 [  6   9   3   6]
 [ 24   3 -12  18]
 [ -9   6  -9   3]]


In [11]:
# Realiza el producto interno con una nueva matriz de dimensiones 4x2.
# Matriz M ya definida
M = np.array([[1, 9, 8, -4],
              [2, 3, 1, 2],
              [8, 1, -4, 6],
              [-3, 2, -3, 1]])

# Nueva matriz N de dimensiones 4x2
N = np.array([[1, 0],
              [0, 1],
              [2, -1],
              [-1, 3]])

# Producto interno: M (4x4) × N (4x2)
producto = np.dot(M, N)

# Mostrar resultado, tiene que ser una matriz de de 4x2
print("Producto interno M × N:\n")
print(producto)

Producto interno M × N:

[[ 21 -11]
 [  2   8]
 [ -6  23]
 [-10   8]]


In [24]:
# 3.a
# El sistema de ecuaciones lo podemos representar como MxV =I
# Entonces M = V-1x I

# Matriz de coeficientes
M = np.array([[1, 2, 5, -4],
              [5, 8, 1, 1],
              [5, 7, -3, 2],
              [-1, 3, 9, -1]])

# Vector de resultados
b = np.array([21, -8, 14, 5])

# Resolver el sistema
solucion = np.linalg.solve(M, b)

# Mostrar resultados redondeados
variables = ['x', 'y', 'z', 'w']
for var, val in zip(variables, solucion.tolist()):
    print(f"{var} = {round(val, 2)}")

x = -57.7
y = 41.32
z = -22.67
w = -27.35


In [28]:
# Comprobación Mx[55,60,17,118] debe dar [21, -8, 14, 5]
M = np.array([
                [1,2,5,-4],
                [5,8,1,1],
                [5,7,-3,2],
                [1,3,9,-1]
                ])

producto = np.dot(M_inv, [[55], [60], [17], [118]])

print(producto)


[[21.]
 [-8.]
 [14.]
 [ 5.]]


In [38]:
# 3.b
M = np.array([
             [6,0,8],
             [2,2,1],
             [4,1,0]
             ])
# Vector de resultados
b = np.array([9,15,-4])

# Resolver el sistema
solucion = np.linalg.solve(M, b)

# Mostrar resultados redondeados
variables = ['x', 'y', 'z']
for var, val in zip(variables, solucion.tolist()):
    print(f"{var} = {round(val, 2)}")

x = -3.24
y = 8.96
z = 3.56


In [40]:
# Comprobación 
producto = np.dot(M, [[-3.24], [8.96], [3.56]])

print(producto)


[[ 9.04]
 [15.  ]
 [-4.  ]]
